name: Python application

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 * * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run
      run: |
        mkdir ~/.aws && echo '${{ secrets.AWS_CREDENTIALS }}' > ~/.aws/credentials
        python main.py -session '${{ secrets.SESSION }}' -api-id '${{ secrets.APP_ID }}' -api-hash '${{ secrets.APP_HASH }}' -c '${{ secrets.CHAT }}' -s '${{ secrets.SEARCH }}'
